name: Build Historic

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - .github/workflows/build-latest.yml
      - README.md
permissions: write-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: [2021, 2020, 2019, 2018]
        scheme: [basic, small, medium, full]
    name: Build [${{ matrix.version}}-${{ matrix.scheme }}]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          load: true
          build-args: |
            VERSION=${{ matrix.version }}
            SCHEME=${{ matrix.scheme }}
          tags: texlive:${{ matrix.version }}-${{ matrix.scheme }}
      - name: Test
        run: |
          docker run --rm texlive:${{ matrix.version }}-${{ matrix.scheme }} pdflatex --version
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{amsfonts}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v $(pwd):/data -w /data texlive:${{ matrix.version }}-${{ matrix.scheme }} pdflatex test.tex
          file test.pdf | grep -q ' PDF '
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            VERSION=${{ matrix.version }}
            SCHEME=${{ matrix.scheme }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/texlive:${{ matrix.version }}-${{ matrix.scheme }}
            ${{ github.repository_owner }}/texlive:${{ matrix.version }}-${{ matrix.scheme }}
      - name: Tag year for scheme-full
        uses: docker/build-push-action@v2
        if: ${{ matrix.scheme == 'full' }}
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            VERSION=${{ matrix.version }}
            SCHEME=${{ matrix.scheme }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/texlive:${{ matrix.version }}
            ${{ github.repository_owner }}/texlive:${{ matrix.version }}
  build-with-doc:
    strategy:
      fail-fast: false
      matrix:
        version: [2021, 2020, 2019, 2018]
        scheme: [basic, small, medium, full]
    name: Build [${{ matrix.version}}-${{ matrix.scheme }}]-doc
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Prepare
        run: |
          sed -i 's#tlpdbopt_install_docfiles 0#tlpdbopt_install_docfiles 1#' texlive.profile
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          load: true
          build-args: |
            VERSION=${{ matrix.version }}
            SCHEME=${{ matrix.scheme }}
          tags: texlive:${{ matrix.version }}-${{ matrix.scheme }}
      - name: Test
        run: |
          docker run --rm texlive:${{ matrix.version }}-${{ matrix.scheme }} pdflatex --version
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{amsfonts}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v $(pwd):/data -w /data texlive:${{ matrix.version }}-${{ matrix.scheme }} pdflatex test.tex
          file test.pdf | grep -q ' PDF '
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            VERSION=${{ matrix.version }}
            SCHEME=${{ matrix.scheme }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/texlive:${{ matrix.version }}-${{ matrix.scheme }}-doc
            ${{ github.repository_owner }}/texlive:${{ matrix.version }}-${{ matrix.scheme }}-doc
      - name: Tag year for scheme-full
        uses: docker/build-push-action@v2
        if: ${{ matrix.scheme == 'full' }}
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            VERSION=${{ matrix.version }}
            SCHEME=${{ matrix.scheme }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/texlive:${{ matrix.version }}-doc
            ${{ github.repository_owner }}/texlive:${{ matrix.version }}-doc
  final:
    name: Clean-up and add README
    if: ${{ always() }}
    needs: [build, build-with-doc]
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged
        uses: dylanratcliffe/delete-untagged-containers@main
        with:
          package_name: texlive
          token: ${{ secrets.PAT }}
          user: ${{ github.repository_owner }}
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWD }}
          repository: ${{ github.repository_owner }}/texlive
          short-description: "Dockerized texlive with various schemes"
          readme-filepath: README.md