---
name: Build Historic

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-historic.yml
      - Dockerfile
      - texlive.profile

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-historic:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        year: [2022, 2021, 2020, 2019, 2018]
    name: Build ${{ matrix.year }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: zydou
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            MIRROR_URL=rsync://mirrors.tuna.tsinghua.edu.cn/tex-historic-archive/systems/texlive/${{matrix.year}}/tlnet-final/
          tags: |
            zydou/texlive:${{ matrix.year }}
      - name: Test
        run: |-
          docker run --rm zydou/texlive:${{ matrix.year }} pdflatex --version
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{amsfonts}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v "$(pwd)":/data -w /data zydou/texlive:${{ matrix.year }} pdflatex test.tex
          file test.pdf | grep -q ' PDF '
