---
name: Build Latest

on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 1 * *
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-latest.yml
      - Dockerfile
      - texlive.profile

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-latest:
    name: latest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: zydou
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            MIRROR_URL=rsync://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet/
          tags: |
            zydou/texlive:latest
            zydou/texlive:2023
      - name: Test
        run: |
          docker run --rm zydou/texlive:latest pdflatex --version
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{amsfonts}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v "$(pwd)":/data -w /data zydou/texlive:latest pdflatex test.tex
          file test.pdf | grep -q ' PDF '
