name: Build Latest VSCode

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-latest-vscode.yml
      - vscode.Dockerfile
      - vscode.sh
  schedule:
    - cron: "0 18 * * *"
permissions: write-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        scheme: [basic, small, medium, full]
    name: Build [2022, latest]-${{ matrix.scheme }}-vscode
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ matrix.scheme != 'full' }}
        with:
          context: .
          file: vscode.Dockerfile
          platforms: linux/amd64
          push: true
          build-args: TAG=latest-${{ matrix.scheme }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/texlive:latest-${{ matrix.scheme }}-vscode
            ghcr.io/${{ github.repository_owner }}/texlive:2022-${{ matrix.scheme }}-vscode
            ${{ github.repository_owner }}/texlive:latest-${{ matrix.scheme }}-vscode
            ${{ github.repository_owner }}/texlive:2022-${{ matrix.scheme }}-vscode
      - name: Tag year only for scheme-full
        uses: docker/build-push-action@v2
        if: ${{ matrix.scheme == 'full' }}
        with:
          context: .
          file: vscode.Dockerfile
          platforms: linux/amd64
          push: true
          build-args: TAG=latest-${{ matrix.scheme }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/texlive:latest-${{ matrix.scheme }}-vscode
            ghcr.io/${{ github.repository_owner }}/texlive:2022-${{ matrix.scheme }}-vscode
            ghcr.io/${{ github.repository_owner }}/texlive:latest-vscode
            ghcr.io/${{ github.repository_owner }}/texlive:2022-vscode
            ${{ github.repository_owner }}/texlive:latest-${{ matrix.scheme }}-vscode
            ${{ github.repository_owner }}/texlive:2022-${{ matrix.scheme }}-vscode
            ${{ github.repository_owner }}/texlive:latest-vscode
            ${{ github.repository_owner }}/texlive:2022-vscode
      - name: Test
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/texlive:latest-${{ matrix.scheme }}-vscode pdflatex --version
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{amsfonts}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v $(pwd):/data -w /data ghcr.io/${{ github.repository_owner }}/texlive:latest-${{ matrix.scheme }}-vscode pdflatex test.tex
          file test.pdf | grep -q ' PDF '
  build-with-doc:
    strategy:
      matrix:
        scheme: [basic, small, medium, full]
    name: Build [2022, latest]-${{ matrix.scheme }}-doc-vscode
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        if: ${{ matrix.scheme != 'full' }}
        with:
          context: .
          file: vscode.Dockerfile
          platforms: linux/amd64
          push: true
          build-args: TAG=latest-${{ matrix.scheme }}-doc
          tags: |
            ghcr.io/${{ github.repository_owner }}/texlive:latest-${{ matrix.scheme }}-doc-vscode
            ghcr.io/${{ github.repository_owner }}/texlive:2022-${{ matrix.scheme }}-doc-vscode
            ${{ github.repository_owner }}/texlive:latest-${{ matrix.scheme }}-doc-vscode
            ${{ github.repository_owner }}/texlive:2022-${{ matrix.scheme }}-doc-vscode
      - name: Tag year only for scheme-full
        uses: docker/build-push-action@v2
        if: ${{ matrix.scheme == 'full' }}
        with:
          context: .
          file: vscode.Dockerfile
          platforms: linux/amd64
          push: true
          build-args: TAG=latest-${{ matrix.scheme }}-doc
          tags: |
            ghcr.io/${{ github.repository_owner }}/texlive:latest-${{ matrix.scheme }}-doc-vscode
            ghcr.io/${{ github.repository_owner }}/texlive:2022-${{ matrix.scheme }}-doc-vscode
            ghcr.io/${{ github.repository_owner }}/texlive:latest-doc-vscode
            ghcr.io/${{ github.repository_owner }}/texlive:2022-doc-vscode
            ${{ github.repository_owner }}/texlive:latest-${{ matrix.scheme }}-doc-vscode
            ${{ github.repository_owner }}/texlive:2022-${{ matrix.scheme }}-doc-vscode
            ${{ github.repository_owner }}/texlive:latest-doc-vscode
            ${{ github.repository_owner }}/texlive:2022-doc-vscode
      - name: Test
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/texlive:latest-${{ matrix.scheme }}-doc-vscode pdflatex --version
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{amsfonts}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v $(pwd):/data -w /data ghcr.io/${{ github.repository_owner }}/texlive:latest-${{ matrix.scheme }}-doc-vscode pdflatex test.tex
          file test.pdf | grep -q ' PDF '
  final:
    name: Clean-up and add README
    if: ${{ always() }}
    needs: [build, build-with-doc]
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged
        uses: dylanratcliffe/delete-untagged-containers@main
        with:
          package_name: texlive
          token: ${{ secrets.PAT }}
          user: ${{ github.repository_owner }}
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWD }}
          repository: ${{ github.repository_owner }}/texlive
          short-description: "Dockerized texlive with various schemes"
          readme-filepath: README.md