name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
      - Dockerfile
      - texlive.profile
jobs:
  build-latest:
    name: latest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            MIRROR_URL=rsync://texlive.info/CTAN/systems/texlive/tlnet/
          tags: |
            ${{ github.repository_owner }}/texlive:latest
            ${{ github.repository_owner }}/texlive:2022
      - name: Test
        run: |
          docker run --rm ${{ github.repository_owner }}/texlive:latest pdflatex --version
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{amsfonts}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v $(pwd):/data -w /data ${{ github.repository_owner }}/texlive:latest pdflatex test.tex
          file test.pdf | grep -q ' PDF '
  build-historic:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        year: [2021, 2020, 2019, 2018]
    name: Build ${{ matrix.year }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            MIRROR_URL=rsync://texlive.info/historic/systems/texlive/${{matrix.year}}/tlnet-final/
          tags: |
            ${{ github.repository_owner }}/texlive:${{ matrix.year }}
      - name: Test
        run: |
          docker run --rm ${{ github.repository_owner }}/texlive:${{ matrix.year }} pdflatex --version
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{amsfonts}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v $(pwd):/data -w /data ${{ github.repository_owner }}/texlive:${{ matrix.year }} pdflatex test.tex
          file test.pdf | grep -q ' PDF '
