---
name: Build Historic

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-historic.yml
      - historic.Dockerfile

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        year: [2023, 2022, 2021, 2020, 2019, 2018]
        base_os: [buster, bullseye, bookworm, trixie, xenial, bionic, focal, jammy]
    name: Build ${{matrix.year}} on ${{ matrix.base_os }}
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        run: |
          # Remove .Net
          sudo rm -rf /usr/share/dotnet
          # Remove Android
          sudo rm -rf /usr/local/lib/android
          # Remove Haskell
          sudo rm -rf /opt/ghc
          # Remove CodeQL
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          # Remove docker images
          sudo docker image prune --all --force
      - name: Set up Git repository
        uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: zydou
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Build and push (trixie)
        if: matrix.base_os == 'trixie'
        uses: docker/build-push-action@master
        with:
          context: .
          file: historic.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          build-args: |
            YEAR=${{matrix.year}}
            BASE_OS=${{matrix.base_os}}
          cache-from: type=registry,ref=zydou/texlive:cache-${{matrix.year}}-${{matrix.base_os}}
          cache-to: type=registry,ref=zydou/texlive:cache-${{matrix.year}}-${{matrix.base_os}},mode=max
          tags: |
            zydou/texlive:${{matrix.year}}
            zydou/texlive:${{matrix.year}}-${{matrix.base_os}}
      - name: Build and push
        if: matrix.base_os != 'trixie'
        uses: docker/build-push-action@master
        with:
          context: .
          file: historic.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          build-args: |
            YEAR=${{matrix.year}}
            BASE_OS=${{matrix.base_os}}
          cache-from: type=registry,ref=zydou/texlive:cache-${{matrix.year}}-${{matrix.base_os}}
          cache-to: type=registry,ref=zydou/texlive:cache-${{matrix.year}}-${{matrix.base_os}},mode=max
          tags: |
            zydou/texlive:${{matrix.year}}-${{matrix.base_os}}
      - name: Test
        run: |-
          docker run --rm zydou/texlive:${{matrix.year}}-${{matrix.base_os}} pdflatex --version
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{amsfonts}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v "$(pwd)":/data -w /data zydou/texlive:${{matrix.year}}-${{matrix.base_os}} pdflatex test.tex
          file test.pdf | grep -q ' PDF '
