---
name: Build Historic

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-historic.yml
      - historic.Dockerfile

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: write-all

jobs:
  build-historic-simplified-suffix:
    strategy:
      fail-fast: false
      matrix:
        year: [2023, 2022, 2021, 2020, 2019, 2018]
        base_os: [trixie]  # use trixie as default base image
    name: Build ${{matrix.year}} on ${{ matrix.base_os }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main
      - name: Delete built-in docker images to get more disk space
        run: docker system prune --all --volumes --force
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: zydou
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Login to GHCR
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          file: historic.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            YEAR=${{matrix.year}}
            BASE_OS=${{matrix.base_os}}
          cache-from: |
            type=registry,ref=ghcr.io/${{github.repository}}:cache-${{matrix.year}}-sources
            type=registry,ref=ghcr.io/${{github.repository}}:cache-${{matrix.base_os}}-baseimg
            type=registry,ref=ghcr.io/${{github.repository}}:cache-${{matrix.year}}-${{matrix.base_os}}
          cache-to: type=registry,ref=ghcr.io/${{github.repository}}:cache-${{matrix.year}}-${{matrix.base_os}},mode=max
          tags: |
            ${{github.repository}}:${{matrix.year}}
            ${{github.repository}}:${{matrix.year}}-${{matrix.base_os}}
            ghcr.io/${{github.repository}}:${{matrix.year}}
            ghcr.io/${{github.repository}}:${{matrix.year}}-${{matrix.base_os}}
      - name: Test
        run: |-
          docker run --rm ${{github.repository}}:${{matrix.year}}-${{matrix.base_os}} pdflatex --version
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{amsfonts}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v "$(pwd)":/data -w /data ${{github.repository}}:${{matrix.year}}-${{matrix.base_os}} pdflatex test.tex
          file test.pdf | grep -q ' PDF '

  build-historic-full-suffix:
    strategy:
      fail-fast: false
      matrix:
        year: [2023, 2022, 2021, 2020, 2019, 2018]
        base_os: [buster, bullseye, bookworm, xenial, bionic, focal, jammy]
    name: Build ${{matrix.year}} on ${{ matrix.base_os }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main
      - name: Delete built-in docker images to get more disk space
        run: docker system prune --all --volumes --force
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: zydou
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Login to GHCR
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          file: historic.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            YEAR=${{matrix.year}}
            BASE_OS=${{matrix.base_os}}
          cache-from: |
            type=registry,ref=ghcr.io/${{github.repository}}:cache-${{matrix.year}}-sources
            type=registry,ref=ghcr.io/${{github.repository}}:cache-${{matrix.base_os}}-baseimg
            type=registry,ref=ghcr.io/${{github.repository}}:cache-${{matrix.year}}-${{matrix.base_os}}
          cache-to: type=registry,ref=ghcr.io/${{github.repository}}:cache-${{matrix.year}}-${{matrix.base_os}},mode=max
          tags: |
            ${{github.repository}}:${{matrix.year}}-${{matrix.base_os}}
            ghcr.io/${{github.repository}}:${{matrix.year}}-${{matrix.base_os}}
      - name: Test
        run: |-
          docker run --rm ${{github.repository}}:${{matrix.year}}-${{matrix.base_os}} pdflatex --version
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{amsfonts}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v "$(pwd)":/data -w /data ${{github.repository}}:${{matrix.year}}-${{matrix.base_os}} pdflatex test.tex
          file test.pdf | grep -q ' PDF '
