---
name: Weekly Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: 42 13 * * 3

permissions: write-all

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: 7 days

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 90
          keep_minimum_runs: 3

      - name: Delete deleted workflow
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_pattern: deleted

      - name: Delete cancelled runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: cancelled

      - name: Delete failure runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: failure

      - name: Delete skipped runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: skipped
