name: Debian Latest

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/debian-latest.yml
      - debian.Dockerfile
      - debian.profile
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          file: debian.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository_owner }}/texlive:debian-latest
            ${{ github.repository_owner }}/texlive:debian-2022

      - name: Test
        run: |
          docker run --rm ${{ github.repository_owner }}/texlive:debian-latest pdflatex --version
          cat <<EOF >test.tex
          \documentclass{article}
          \usepackage{amsfonts}
          \begin{document}
          test
          \end{document}
          EOF
          docker run --rm -v $(pwd):/data -w /data ${{ github.repository_owner }}/texlive:debian-latest pdflatex test.tex
          file test.pdf | grep -q ' PDF '
