name: Mirror Historic

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/mirror-historic.yml
      - mirrors/mirror-historic.Dockerfile
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        year: [2021, 2020, 2019, 2018]
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          file: mirrors/mirror-historic.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            YEAR=${{ matrix.year }}
          tags: |
            ${{ github.repository_owner }}/texlive:mirror-${{ matrix.year }}
