name: Mirror

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/mirror.yml
      - mirrors/mirror.Dockerfile
  schedule:
    - cron: "45 18 15 * *"

permissions: write-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWD }}
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          file: mirrors/mirror.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository_owner }}/texlive:mirror